import type { Metadata } from "next";
import { Poppins } from 'next/font/google'; // Poppins font import
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <Toaster />
        {/* Wrapped server component inside client component */}
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
